version: 2
jobs:
  "node-11":
    docker:
      - image: circleci/node:11
    working_directory: ~/asynctools
    steps:
      - checkout

      - run: npm install
      - run: npm test
      - run: npm run coverage

  "node-10":
    docker:
      - image: circleci/node:10
    working_directory: ~/asynctools
    steps:
      - checkout

      - run: npm install
      - run: npm test
  "deployed":
    docker:
      - image: circleci/node:10
      working_directory: ~/asynctools
      steps:
        - checkout
        - run: cd examples && npm install && npm test

workflows:
  version: 2
  build:
    jobs:
      - "node-11"
      - "node-10"
      - "deployed"
