version: 2
jobs:
  "node-12":
    docker:
      - image: circleci/node:12
    working_directory: ~/asynctools
    steps:
      - checkout

      - run: npm install
      - run: npm test

  "node-10":
    docker:
      - image: circleci/node:10
    working_directory: ~/asynctools
    steps:
      - checkout

      - run: npm install
      - run: npm test
  "deployed":
    docker:
      - image: circleci/node:10
    working_directory: ~/asynctools
    steps:
      - checkout
      - run: cd examples && npm install && npm test

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
       - "deployed"
  build:
    jobs:
      - "node-12"
      - "node-10"
      - "deployed"
