version: 2
jobs:
  "node-13":
    docker:
      - image: circleci/node:13
    working_directory: ~/asynctools
    steps:
      - checkout

      - run: npm install
      - run: npm test
      - run: npm run test:ci
      - store_test_results:
          path: ~/asynctools/reports
  "node-12":
    docker:
      - image: circleci/node:12
    working_directory: ~/asynctools
    steps:
      - checkout

      - run: npm install
      - run: npm test
      - run: npm run test:ci
      - store_test_results:
          path: ~/asynctools/reports

  "node-10":
    docker:
      - image: circleci/node:10
    working_directory: ~/asynctools
    steps:
      - checkout

      - run: npm install
      - run: npm test
      - run: npm run test:ci
      - store_test_results:
          path: ~/asynctools/reports
  "deployed":
    docker:
      - image: circleci/node:10
    working_directory: ~/asynctools
    steps:
      - checkout
      - run: cd examples && npm install && npm test

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - "master"
    jobs:
      - "deployed"
  build:
    jobs:
      - "node-13"
      - "node-12"
      - "node-10"
      - "deployed"
